name: Terraform EKS Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:

permissions:
  id-token: write   # required for GitHub OIDC → AWS
  contents: read  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.12.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
